void motorInit(void);
void moveX(int);
void moveY(int);
void moveZ(int);
void moveXSlow(int);
void moveYSlow(int);
void moveZSlow(int);
void moveMotor(int,int);
void moveMotorSlow(int,int);
void enableMotors(void);
void disableMotors(void);
//void TIM3_IRQHandler(void);
void delayUs(int uS);
