void motorInit(void);
void moveX(int);
void moveY(int);
void moveZ(int);
void moveP(int);
void moveN(int);
void moveXSlow(int);
void moveYSlow(int);
void moveZSlow(int);
void moveMotor(int,int);
void moveMotorSlow(int,int);
void enableMotors(void);
void disableMotors(void);
void homeMotors(void);
void phiHome(void);
void moveMotorDeg(int);
void nonRecoverableError(void);
void delayUs(int uS);
